#!/bin/bash

# ─── CONFIG ──────────────────────────
lsblk
read -p "Disk (e.g. nvme0n1,sda): " DISK
while :; do
  read -s -p "LUKS Password: " P; echo
  read -s -p "Confirm: " C; echo
  [ "$P" = "$C" ] && break || echo "Mismatch" >&2
done
CRYPTPASS="$P"


# ─── Partition ──────────────────────────
sgdisk -n33:0:0    -t33:8309 /dev/$DISK 
partprobe /dev/$DISK
udevadm settle
lsblk /dev/$DISK
read -p "EFI Partition (eg- sda1, nvme0n1p1): " EFI
read -p "Root Partition (eg- sda2,nvme0n1p2): " ROOT

# ─── Encrypt ──────────────────────────
echo -n "$CRYPTPASS" | cryptsetup luksFormat --type luks2 /dev/$ROOT -
echo -n "$CRYPTPASS" | cryptsetup open /dev/$ROOT cryptroot -

# ─── Format ──────────────────────────
mkfs.ext4 /dev/mapper/cryptroot

# ─── Mount ──────────────────────────
mount /dev/mapper/cryptroot /mnt
mkdir -p /mnt/boot
mount /dev/$EFI /mnt/boot

# ─── Hardware ──────────────────────────
CPU=$(lscpu | grep "Model name")
[[ "$CPU" == *Intel* ]] && UC="intel-ucode" || UC="amd-ucode"

# ─── Mirrors ──────────────────────────
cat > /etc/pacman.d/mirrorlist << 'EOF'
Server = https://mirror.freedif.org/archlinux/$repo/os/$arch
Server = https://mirrors.dotsrc.org/archlinux/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
EOF

# ─── Install ──────────────────────────
pacman-key --init
pacman-key --populate archlinux
pacman -Sy --noconfirm archlinux-keyring
pacstrap -K /mnt base base-devel linux-lts linux-firmware $UC nvim efibootmgr zsh networkmanager
genfstab -U /mnt >> /mnt/etc/fstab

# ─── Copy chroot script ──────────────────────────
curl -LO https://raw.githubusercontent.com/khruso/syra-t3/main/syra-t3-2
cp syra-t3-2 /mnt/syra-t3-2
chmod +x /mnt/syra-t3-2
arch-chroot /mnt bash syra-t3-2 && rm /mnt/syra-t3-2

# ─── Exit ──────────────────────────
umount -R /mnt
cryptsetup close cryptroot
echo "Installation DONE. Reboot."
